/**
 * Free, no-API drive time estimate — a hardcoded table of real-world drive
 * times FROM WINSTON, OR (Lukas's home base) TO each city he might get a
 * lead/booking from. No geometry, no routing engine, just known Oregon
 * highway drive times so short valley hops read short and coastal/mountain
 * roads read appropriately slow (a generic straight-line-distance formula
 * can't tell a flat I-5 shot from a curvy 2-lane highway apart, which is
 * why this replaced that approach). Fixed to Winston for now — if the home
 * base ever needs to be configurable, this table would need to become
 * per-origin, but that's not worth the complexity until it's actually
 * needed. Returns null for any city not listed rather than guessing.
 */

const DRIVE_TIME_FROM_WINSTON: Record<string, string> = {
  winston: "~5 min drive",
  roseburg: "~10 min drive",
  "myrtle creek": "~15 min drive",
  riddle: "~15 min drive",
  sutherlin: "~20 min drive",
  canyonville: "~25 min drive",
  glide: "~25 min drive",
  elkton: "~35 min drive",
  "days creek": "~30 min drive",
  yoncalla: "~30 min drive",
  drain: "~35 min drive",
  scottsburg: "~45 min drive",
  "cottage grove": "~55 min drive",
  reedsport: "~55 min drive",
  "winchester bay": "~1h drive",
  "gold hill": "~1h 15m drive",
  "pleasant hill": "~1h 15m drive",
  "grants pass": "~1h 5m drive",
  creswell: "~1h 20m drive",
  "rogue river": "~1h 20m drive",
  elmira: "~1h 20m drive",
  veneta: "~1h 25m drive",
  springfield: "~1h 25m drive",
  eugene: "~1h 30m drive",
  medford: "~1h 30m drive",
  cheshire: "~1h 30m drive",
  "central point": "~1h 40m drive",
  jacksonville: "~1h 40m drive",
  "coos bay": "~1h 40m drive",
  "junction city": "~1h 40m drive",
  phoenix: "~1h 50m drive",
  harrisburg: "~1h 45m drive",
  florence: "~1h 45m drive",
  "north bend": "~1h 45m drive",
  talent: "~1h 55m drive",
  philomath: "~1h 55m drive",
  oakridge: "~1h 55m drive",
  ashland: "~2h drive",
  corvallis: "~2h drive",
  albany: "~2h 5m drive",
  independence: "~2h 15m drive",
  dallas: "~2h 15m drive",
  lebanon: "~2h 15m drive",
  newport: "~2h 55m drive",
  "sweet home": "~2h 25m drive",
  salem: "~2h 30m drive",
  keizer: "~2h 30m drive",
  mcminnville: "~2h 30m drive",
  sheridan: "~2h 30m drive",
  "lincoln city": "~3h 15m drive",
  monmouth: "~2h 45m drive",
  silverton: "~2h 45m drive",
  woodburn: "~2h 45m drive",
  wilsonville: "~2h 40m drive",
  sherwood: "~2h 45m drive",
  "klamath falls": "~2h 45m drive",
  beaverton: "~2h 50m drive",
  tigard: "~2h 50m drive",
  hillsboro: "~2h 55m drive",
  "oregon city": "~2h 55m drive",
  molalla: "~2h 55m drive",
  portland: "~3h drive",
  bend: "~3h drive",
  tillamook: "~3h drive",
  gresham: "~3h 10m drive",
  estacada: "~3h 10m drive",
  redmond: "~3h 5m drive",
  sandy: "~3h 15m drive",
  prineville: "~3h 15m drive",
  madras: "~3h 20m drive",
  "the dalles": "~3h 30m drive",
  astoria: "~3h 45m drive",
  "hood river": "~3h 45m drive",
  lakeview: "~4h drive",
  burns: "~4h drive",
  pendleton: "~4h 45m drive",
  "john day": "~4h 30m drive",
  "la grande": "~5h 15m drive",
  "baker city": "~5h 45m drive",
  ontario: "~6h 30m drive",
  // Added 2026-10-10: every city with a listing in the last 60 days that was
  // missing, which was 290 of 1,800 listings. Estimates, not measured.
  winchester: "~15 min drive",
  tenmile: "~15 min drive",
  oakland: "~25 min drive",
  "camas valley": "~25 min drive",
  umpqua: "~30 min drive",
  azalea: "~40 min drive",
  glendale: "~50 min drive",
  coquille: "~1h 10m drive",
  lakeside: "~1h 15m drive",
  bandon: "~1h 35m drive",
  merlin: "~1h 10m drive",
  wilderville: "~1h 20m drive",
  selma: "~1h 30m drive",
  williams: "~1h 35m drive",
  "cave junction": "~1h 40m drive",
  "central pt": "~1h 40m drive",
  "white city": "~1h 40m drive",
  "eagle point": "~1h 45m drive",
  "eagle pt": "~1h 45m drive",
  "shady cove": "~1h 55m drive",
  trail: "~2h 5m drive",
  lorane: "~1h 15m drive",
  coburg: "~1h 35m drive",
  lowell: "~1h 40m drive",
  noti: "~1h 40m drive",
  marcola: "~1h 45m drive",
  walterville: "~1h 45m drive",
  mapleton: "~2h drive",
  "blue river": "~2h 15m drive",
  monroe: "~1h 50m drive",
  brownsville: "~1h 55m drive",
  halsey: "~1h 55m drive",
  jefferson: "~2h 15m drive",
  blodgett: "~2h 20m drive",
  turner: "~2h 25m drive",
  scio: "~2h 30m drive",
  aumsville: "~2h 30m drive",
  stayton: "~2h 35m drive",
  amity: "~2h 35m drive",
  sublimity: "~2h 40m drive",
  aurora: "~2h 40m drive",
  hubbard: "~2h 40m drive",
  lafayette: "~2h 45m drive",
  canby: "~2h 45m drive",
  tualatin: "~2h 45m drive",
  lyons: "~2h 50m drive",
  "mount angel": "~2h 50m drive",
  newberg: "~2h 50m drive",
  dundee: "~2h 50m drive",
  carlton: "~2h 50m drive",
  "lake oswego": "~2h 50m drive",
  "west linn": "~2h 50m drive",
  "mill city": "~2h 55m drive",
  milwaukie: "~3h drive",
  clackamas: "~3h drive",
  "happy valley": "~3h 5m drive",
  cornelius: "~3h 5m drive",
  "north plains": "~3h 5m drive",
  "forest grove": "~3h 10m drive",
  troutdale: "~3h 15m drive",
  boring: "~3h 15m drive",
  yachats: "~2h 20m drive",
  waldport: "~2h 30m drive",
  "seal rock": "~2h 40m drive",
  tidewater: "~2h 45m drive",
  "south beach": "~2h 45m drive",
  toledo: "~2h 55m drive",
  "otter rock": "~3h 5m drive",
  "depoe bay": "~3h 10m drive",
  "gleneden beach": "~3h 15m drive",
  neotsu: "~3h 20m drive",
  otis: "~3h 20m drive",
  neskowin: "~3h 25m drive",
  cloverdale: "~3h 30m drive",
  "pacific city": "~3h 35m drive",
  "bay city": "~3h 55m drive",
  oceanside: "~4h drive",
  netarts: "~4h drive",
  "rockaway beach": "~4h 5m drive",
  wheeler: "~4h 15m drive",
  nehalem: "~4h 20m drive",
  manzanita: "~4h 20m drive",
};

function normalizeCity(city: string): string {
  return city.trim().toLowerCase();
}

/** Rough "~1h 30m drive" from Winston, OR, or null if the city isn't in the table. */
export function estimateDriveTime(city: string): string | null {
  return DRIVE_TIME_FROM_WINSTON[normalizeCity(city)] ?? null;
}

/** The same one-way estimate as whole minutes (e.g. "~1h 15m drive" → 75), or null if the city isn't in the table. */
export function estimateDriveMinutes(city: string): number | null {
  const label = estimateDriveTime(city);
  if (!label) return null;
  const hours = Number(label.match(/(\d+)h/)?.[1] ?? 0);
  const minutes = Number(label.match(/(\d+)\s*min|(\d+)m\b/)?.slice(1).find(Boolean) ?? 0);
  return hours * 60 + minutes || null;
}
