export interface LuxuryAgent {
  name: string;
  email: string;
  phone: string | null;
  brokerage: string;
  city: string;
  state: string;
  sourceUrl: string;
}

export const luxuryVideoAgents: LuxuryAgent[] = [
  {
    name: "Love Oregon.House Ashley Jensen",
    email: "ashley@mind.net",
    phone: "541-324-2620",
    brokerage: "Ashley Jensen",
    city: "Eagle Point",
    state: "OR",
    sourceUrl: "https://loveoregon.house/",
  },
  {
    name: "Erik Leland",
    email: "erik@lelandnw.com",
    phone: null,
    brokerage: "Erik Leland",
    city: "Lake Oswego",
    state: "OR",
    sourceUrl: "https://lelandnw.com/",
  },
  {
    name: "Alex Larson",
    email: "alex@martinoutdoorproperties.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Alice Lema",
    email: "alicelema@alicelema.com",
    phone: "541-301-7980",
    brokerage: "Alice Lema",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://alicelema.com/agents",
  },
  {
    name: "Ashley Lacer",
    email: "ashley@martinoutdoorproperties.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Chris Martin",
    email: "chris@martinoutdoorproperties.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Evan Kaseberg",
    email: "evan@landandwildlife.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Francisco Gomez",
    email: "francisco@rockwellrealestate.com",
    phone: "541-951-4865",
    brokerage: "Rockwell Real Estate Group",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://rockwellrealestate.com/agents",
  },
  {
    name: "Mike Lee",
    email: "mikelee519@hotmail.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Sam Terrell",
    email: "sam@martinoutdoorproperties.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Shannon Forrest",
    email: "shannon@martinoutdoorproperties.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Wes Walton",
    email: "wes@landandwildlife.com",
    phone: null,
    brokerage: "Chris Martin",
    city: "Medford",
    state: "OR",
    sourceUrl: "https://martinoutdoorproperties.com/meet-the-team/",
  },
  {
    name: "Barbara Greenman",
    email: "greenman.barbara@yahoo.com",
    phone: null,
    brokerage: "Greenman Properties",
    city: "Newberg",
    state: "OR",
    sourceUrl: "https://greenmanproperties.com/agent/barbara-greenman/",
  },
  {
    name: "Rita Wolff",
    email: "rita@ritawolff.com",
    phone: "503-504-5258",
    brokerage: "Rita Wolff",
    city: "Newberg",
    state: "OR",
    sourceUrl: "https://oregonwinecountryproperties.com/",
  },
  {
    name: "Tori Nicol",
    email: "torinicol.cbpg@outlook.com",
    phone: "503-860-3923",
    brokerage: "Tori Nicol",
    city: "Newberg",
    state: "OR",
    sourceUrl: "https://torinicol.com/",
  },
  {
    name: "Elizabeth Davidson",
    email: "elizabeth@elizabethdavidson.com",
    phone: "503-939-2035",
    brokerage: "Elizabeth Davidson",
    city: "Portland",
    state: "OR",
    sourceUrl: "https://elizabethdavidson.com/",
  },
  {
    name: "Leilani Powell",
    email: "leilanipdx@gmail.com",
    phone: "503-804-0587",
    brokerage: "Portland OR Home",
    city: "Portland",
    state: "OR",
    sourceUrl: "https://portlandorhome.com/",
  },
  {
    name: "Matt Tackett",
    email: "matt@mportlandhomes.com",
    phone: "503-385-5585",
    brokerage: "Matt Tackett",
    city: "Willamette Valley",
    state: "OR",
    sourceUrl: "https://www.oregonvineyardproperty.com/our-team/",
  },
];
