// GENERATED by scripts/warmGuard.ts -- do not edit by hand.
//
// Source:   scrape/v2/FINAL-send-standard-agents.csv (405 rows)
// Screened: 358 sendable, all segment=standard
// Held:     38 fuzzy-match reviews, 1 known-agent block, 1 business name,
//           7 already sent by an aborted first run (caught by email)
//
// Every row below cleared the warm-agent guard in scripts/lib/warmGuard.mjs —
// no shared email or phone with an agent we have a relationship with, and no
// name that fuzzy-matches one. coldOutreachApiRunner.ts re-runs that same
// screen before sending and aborts if anything here has stopped being safe.

import type { Candidate } from "./lib/warmGuardScreen";

export const candidates: Candidate[] = [
  {
    "name": "Lisa Lang",
    "email": "soldbylisalang@gmail.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "ALBANY"
  },
  {
    "name": "Christine Kites",
    "email": "christine.kites@exprealty.com",
    "phone": "541-231-4535",
    "brokerage": "EXP REALTY, LLC",
    "city": "ALBANY"
  },
  {
    "name": "Lisa Hoefer",
    "email": "lisa@hubcitypm.com",
    "phone": null,
    "brokerage": "HUB CITY PROPERTY MANAGEMENT",
    "city": "ALBANY"
  },
  {
    "name": "Sonja Neperud",
    "email": "sonjaneperud@aol.com",
    "phone": null,
    "brokerage": "WESTERN HOMES REALTY COMPANY",
    "city": "ALBANY"
  },
  {
    "name": "Brian Oare",
    "email": "bw.oare@oarerealty.com",
    "phone": null,
    "brokerage": "Oare & Associates Realty",
    "city": "ALBANY"
  },
  {
    "name": "Dieter Wehner",
    "email": "dieter@ihomesweb.com",
    "phone": null,
    "brokerage": "IHOMES",
    "city": "ALBANY"
  },
  {
    "name": "Andrea Butcher",
    "email": "andrea.butcher@rhss.com",
    "phone": null,
    "brokerage": "REALHome Services and Solutions, Inc.",
    "city": "ALPHARETTA"
  },
  {
    "name": "Sherri Blanton",
    "email": "sherrib@sherriblantonrealestate.com",
    "phone": null,
    "brokerage": "SHERRI BLANTON REAL ESTATE LLC",
    "city": "ASHLAND"
  },
  {
    "name": "Amber Boyle",
    "email": "amber@avenuenwrealty.com",
    "phone": null,
    "brokerage": "AVENUE NW REALTY",
    "city": "BEND"
  },
  {
    "name": "Dana Furlan",
    "email": "dana@danafurlan.com",
    "phone": "541-771-8761",
    "brokerage": "EXP REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "Dayna Lanning",
    "email": "daynalanning@gmail.com",
    "phone": null,
    "brokerage": "Knightsbridge International Real Estate, LLC",
    "city": "BEND"
  },
  {
    "name": "Dawn Newton",
    "email": "dawn@remingtonrealtors.com",
    "phone": null,
    "brokerage": "REMINGTON REAL ESTATE LLC",
    "city": "BEND"
  },
  {
    "name": "Peggi Schoning",
    "email": "pschoning@roguerealestate.com",
    "phone": null,
    "brokerage": "HOMESMART REALTY PROS",
    "city": "BEND"
  },
  {
    "name": "Robert Eggers",
    "email": "rob@bendhomeguide.com",
    "phone": null,
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "Michelle Rea",
    "email": "rearealestate@gmail.com",
    "phone": null,
    "brokerage": "Engel & Voelkers Bend",
    "city": "BEND"
  },
  {
    "name": "Mary Gemba",
    "email": "bendproperties@gmail.com",
    "phone": null,
    "brokerage": "DESCHUTES REALTY",
    "city": "BEND"
  },
  {
    "name": "Patricia Dempsey",
    "email": "patty.dempsey@theagencyre.com",
    "phone": null,
    "brokerage": "THE AGENCY BEND",
    "city": "BEND"
  },
  {
    "name": "Jefferey Crafton",
    "email": "jeff@stellarnw.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Tiffany Paulin",
    "email": "tiffany@oregonranchproperty.com",
    "phone": null,
    "brokerage": "LIVOREGON REAL ESTATE LLC",
    "city": "BEND"
  },
  {
    "name": "Angela Arnett",
    "email": "angie@stellarnw.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Brook Gardner",
    "email": "brook@brookgardner.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Daniel Cook",
    "email": "dan@dancookrealestate.com",
    "phone": null,
    "brokerage": "1 Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "BEND"
  },
  {
    "name": "Terry Denoux",
    "email": "terryd@gobend.com",
    "phone": null,
    "brokerage": "WORKS REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Misty Rupe",
    "email": "misty.alexanderrupe@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "BEND"
  },
  {
    "name": "Kip Lohr",
    "email": "kip@lohrgroup.pro",
    "phone": null,
    "brokerage": "EPIQUE REALTY",
    "city": "BEND"
  },
  {
    "name": "Kristin Bryan",
    "email": "kristin.l.bryan@gmail.com",
    "phone": null,
    "brokerage": "Knipe Realty ERA Powered",
    "city": "BEND"
  },
  {
    "name": "Inez Martin",
    "email": "inez@thegarnergroup.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Heather Coleman",
    "email": "heather@stellarnw.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Christin Hunter",
    "email": "christin.hunter@theagencyre.com",
    "phone": null,
    "brokerage": "THE AGENCY BEND",
    "city": "BEND"
  },
  {
    "name": "Carey Mcquate",
    "email": "carey@mcquaterealestate.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Heather Wright",
    "email": "heather@wrightathomeproperties.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Oleta Yancey",
    "email": "oleta@thegarnergroup.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Molly Brundage",
    "email": "mollybrundage@icloud.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Ginny Kansas-meszaros",
    "email": "ginny.m.kansas@gmail.com",
    "phone": null,
    "brokerage": "Ginny Kansas Real Estate",
    "city": "BEND"
  },
  {
    "name": "Kenneth Olson",
    "email": "kenolsonrealestate@msn.com",
    "phone": null,
    "brokerage": "TRILLIUM NW PROPERTIES",
    "city": "BEND"
  },
  {
    "name": "Alix Keel",
    "email": "alixheller2020@gmail.com",
    "phone": "458-600-6322",
    "brokerage": "EXP REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "Ryan McGlone",
    "email": "ryan@teammcglone.com",
    "phone": "541-647-2918",
    "brokerage": "EXP REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "Christopher Lawrence",
    "email": "reo@trilrealty.com",
    "phone": null,
    "brokerage": "Trillionaire Realty",
    "city": "BRANSON"
  },
  {
    "name": "Sydney Shapiro",
    "email": "sydney.shapiro@exprealty.com",
    "phone": "541-646-8758",
    "brokerage": "EXP REALTY, LLC",
    "city": "CENTRAL POINT"
  },
  {
    "name": "Jasmine Pham",
    "email": "jasmine.pham@ymail.com",
    "phone": null,
    "brokerage": "HOMETRUST REAL ESTATE LLC",
    "city": "CLACKAMAS"
  },
  {
    "name": "Lisa Gutierrez",
    "email": "mcpier@gmail.com",
    "phone": null,
    "brokerage": "MCCORMICK PIER REALTY L.L.C.",
    "city": "CLACKAMAS"
  },
  {
    "name": "Gerald Aldrich",
    "email": "rebroker.geraldaldrich@gmail.com",
    "phone": null,
    "brokerage": "Taylor & Taylor Realty Co",
    "city": "CLARK FORK"
  },
  {
    "name": "Marguerite Cummings",
    "email": "meg-3rivers@hotmail.com",
    "phone": null,
    "brokerage": "LAKE CHINOOK REALTY",
    "city": "CULVER"
  },
  {
    "name": "Michael Kanfer",
    "email": "michael@cascadevillagerealty.com",
    "phone": null,
    "brokerage": "CASCADE VILLAGE REALTY",
    "city": "DANA POINT"
  },
  {
    "name": "David Holland",
    "email": "dave@bendliving.com",
    "phone": null,
    "brokerage": "Evans, Elder, Brown & Seubert, Inc.",
    "city": "EUGENE"
  },
  {
    "name": "Charles Broughton",
    "email": "charlesbroughton2@gmail.com",
    "phone": null,
    "brokerage": "Country Green Realty LLC",
    "city": "EUGENE"
  },
  {
    "name": "Carly Pederson",
    "email": "carly@carlypedersonteam.com",
    "phone": "541-513-4991",
    "brokerage": "EXP REALTY, LLC",
    "city": "EUGENE"
  },
  {
    "name": "Shannali McCord",
    "email": "shannalimccord@gmail.com",
    "phone": null,
    "brokerage": "FATHOM REALTY OREGON, LLC",
    "city": "FLORENCE"
  },
  {
    "name": "David Prulhiere",
    "email": "david@redwoodrealestate.net",
    "phone": "541-218-5778",
    "brokerage": "EXP REALTY, LLC",
    "city": "GRANTS PASS"
  },
  {
    "name": "Dwayne Yunker",
    "email": "dwayne.yunker@gmail.com",
    "phone": "541-218-6465",
    "brokerage": "EXP REALTY, LLC",
    "city": "GRANTS PASS"
  },
  {
    "name": "Daniel Mal",
    "email": "dan@malandseitz.com",
    "phone": null,
    "brokerage": "HOTSPOTS REAL ESTATE",
    "city": "GRESHAM"
  },
  {
    "name": "Katherine Beymer",
    "email": "beymerteam@gmail.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "GRESHAM"
  },
  {
    "name": "Ben Botofan",
    "email": "benbhomes@yahoo.com",
    "phone": null,
    "brokerage": "MAL & SEITZ",
    "city": "HAPPY VALLEY"
  },
  {
    "name": "Jennifer Maben",
    "email": "jennifer@jennifermaben.com",
    "phone": null,
    "brokerage": "Harcourts Real Estate Network Group",
    "city": "HAPPY VALLEY"
  },
  {
    "name": "Dennis Kviz",
    "email": "dennis@realtordennispdx.com",
    "phone": null,
    "brokerage": "UNIQUE REALT",
    "city": "HILLSBORO"
  },
  {
    "name": "Farah Seibel",
    "email": "farah.seibel@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "HILLSBORO"
  },
  {
    "name": "Max Chau",
    "email": "maxchau@mac.com",
    "phone": null,
    "brokerage": "FIBONACCI REALTY",
    "city": "HILLSBORO"
  },
  {
    "name": "Toni Mikel",
    "email": "toni@pdxbluebird.com",
    "phone": null,
    "brokerage": "BLUEBIRD REAL ESTATE",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Cory Carlson",
    "email": "cory@constantcommercial.com",
    "phone": null,
    "brokerage": "Constant Commercial Real Estate Inc",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Andrew Arthur",
    "email": "aarthurpdx@gmail.com",
    "phone": null,
    "brokerage": "Sunline Realty Group, LLC",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Kim Carty",
    "email": "kim@kimcarty.com",
    "phone": null,
    "brokerage": "SOLDERA PROPERTIES, INC.",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Lisa Hanna",
    "email": "lisa@hannaproperties.net",
    "phone": null,
    "brokerage": "Eleete Real Estate",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Pat Bangerter",
    "email": "pat.bangerter@eleetere.com",
    "phone": null,
    "brokerage": "Eleete Real Estate",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Delita Cordes",
    "email": "delitacore@gmail.com",
    "phone": "541-777-0028",
    "brokerage": "SCOUT REALTY LLC",
    "city": "MADRAS"
  },
  {
    "name": "Joseph Mcdonald",
    "email": "joe@dreamsrealtygrp.com",
    "phone": null,
    "brokerage": "Dreams Realty Group, LLC",
    "city": "MADRAS"
  },
  {
    "name": "Kimberly Parmon",
    "email": "kim@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "MILWAUKIE"
  },
  {
    "name": "Joseph Findling",
    "email": "joe@joeopensdoors.com",
    "phone": null,
    "brokerage": "SUMMA REALTY, INC.",
    "city": "MILWAUKIE"
  },
  {
    "name": "Roger Lowe",
    "email": "roger@lowesflatfee.com",
    "phone": null,
    "brokerage": "LOWES FLAT FEE REALTY A HOMEZU PARTNER",
    "city": "NAMPA"
  },
  {
    "name": "William Johnson",
    "email": "bill@drslisting.com",
    "phone": null,
    "brokerage": "WILLIAM JOHNSON",
    "city": "OCEANSIDE"
  },
  {
    "name": "Cheryle Clunes",
    "email": "cheryle@cheryleclunes.com",
    "phone": null,
    "brokerage": "SOLDERA PROPERTIES, INC.",
    "city": "OREGON CITY"
  },
  {
    "name": "Karen Wu",
    "email": "karenwu.hrp@gmail.com",
    "phone": null,
    "brokerage": "HABITAT RESOURCE PROPERTIES",
    "city": "OREON CITY"
  },
  {
    "name": "Lisa O'Bannon",
    "email": "lisa@troyteam.com",
    "phone": null,
    "brokerage": "KELLER WILLIAMS REALTY PROFESSIONALS",
    "city": "PORTLAND"
  },
  {
    "name": "Thalia Pellicori",
    "email": "thalia@stellarealty.com",
    "phone": null,
    "brokerage": "Stella Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Amy Rhew",
    "email": "amy@thisisfort.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Mason Saxton",
    "email": "fsrcorp08@gmail.com",
    "phone": null,
    "brokerage": "FULL SPEED REALTY, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Thomas Patterson",
    "email": "tom@belroserealtors.com",
    "phone": null,
    "brokerage": "Belrose Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Ryan Purdy",
    "email": "ryan@purdysproperties.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Jennifer Watson",
    "email": "jennifer@propertycollective.net",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Jarrett Altman",
    "email": "jarrett@nworksrealty.com",
    "phone": null,
    "brokerage": "NEIGHBORHOOD WORKS, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Tyler Koski",
    "email": "tyler@grandunionre.com",
    "phone": null,
    "brokerage": "GRAND UNION REAL ESTATE",
    "city": "PORTLAND"
  },
  {
    "name": "Darrin Amico",
    "email": "team@theamicogroup.com",
    "phone": null,
    "brokerage": "AMICO GROUP REALTY",
    "city": "PORTLAND"
  },
  {
    "name": "Shannon Sansoterra",
    "email": "ssansoterra@gmail.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Parvaneh Kalantari",
    "email": "parvaneh@vitalityhomerealty.com",
    "phone": null,
    "brokerage": "VITALITY HOME REALTY, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Michael Shall",
    "email": "mytshall@gmail.com",
    "phone": null,
    "brokerage": "RMS Investment Real Estate LLC",
    "city": "PORTLAND"
  },
  {
    "name": "David Keys",
    "email": "davidk@norris-stevens.com",
    "phone": null,
    "brokerage": "NORRIS & STEVENS, INC.",
    "city": "PORTLAND"
  },
  {
    "name": "Benjamin Ficker",
    "email": "ben@pdxinvest.com",
    "phone": null,
    "brokerage": "RareBird Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Jason Waxberg",
    "email": "jason@equitypacificrealestate.com",
    "phone": null,
    "brokerage": "EQUITY PACIFIC REAL ESTATE LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Sunny Hildebrand",
    "email": "sunny@hildebrandrealty.com",
    "phone": null,
    "brokerage": "HILDEBRAND REALTY",
    "city": "PORTLAND"
  },
  {
    "name": "Amanda Hagen",
    "email": "amanda@amandahagen.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Cassandra Skelley",
    "email": "cassandra1127@msn.com",
    "phone": null,
    "brokerage": "PDX Dwellings, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Hope Beraka",
    "email": "hope@think-portland.com",
    "phone": null,
    "brokerage": "THINK COMMERCIAL LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Lance Marrs",
    "email": "lance@portlandmodern.com",
    "phone": null,
    "brokerage": "PORTLAND MODERN REAL ESTATE",
    "city": "PORTLAND"
  },
  {
    "name": "Timothy Pitts",
    "email": "tim@proud-realty.com",
    "phone": null,
    "brokerage": "PROUD REALTY LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Gustavo Sanchez",
    "email": "gus.sanchez@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "PORTLAND"
  },
  {
    "name": "Eric Hagstette",
    "email": "eric@inhabitre.com",
    "phone": null,
    "brokerage": "INHABIT REAL ESTATE",
    "city": "PORTLAND"
  },
  {
    "name": "Devin Arthurs",
    "email": "devinsellspdx@gmail.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Charity Chesnek",
    "email": "cchesnek@gmail.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Bonnie Roseman",
    "email": "hello@rosemanteam.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Janikka Byman",
    "email": "janikkabyman@gmail.com",
    "phone": null,
    "brokerage": "GRAND UNION REAL ESTATE",
    "city": "PORTLAND"
  },
  {
    "name": "Sanam Dowlatdad",
    "email": "sam@where-inc.com",
    "phone": null,
    "brokerage": "(W)HERE REAL ESTATE COLLABORATIVE",
    "city": "PORTLAND"
  },
  {
    "name": "Hollis Burton",
    "email": "holly@urbannestpdx.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Daniel Brooks",
    "email": "daniel@lovejoyrealestate.com",
    "phone": null,
    "brokerage": "Lovejoy Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Barbara Crowley",
    "email": "bcrowley@bonnycrowley.com",
    "phone": null,
    "brokerage": "PORTLAND PRINCIPAL REALTY, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Phillip Barry",
    "email": "phil@barryinvestmentre.com",
    "phone": null,
    "brokerage": "BARRY INVESTMENT REAL ESTATE LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Adiam Mehretab",
    "email": "adiam@knockpropertymanagement.com",
    "phone": null,
    "brokerage": "KNOCK PROPERTY MANAGEMENT AND REAL ESTATE, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "CRISTEN Lincoln",
    "email": "cristen@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Andrew Misk",
    "email": "andrew.misk@theagencyre.com",
    "phone": null,
    "brokerage": "TAP REFERRAL ONLY LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Maureen Swan",
    "email": "maureen.m.swan@gmail.com",
    "phone": null,
    "brokerage": "Portland Proper Real Estate LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Charles Ramsay",
    "email": "ramsayrealestate@gmail.com",
    "phone": null,
    "brokerage": "EPIQUE REALTY",
    "city": "PORTLAND"
  },
  {
    "name": "Pamela Blair",
    "email": "pam@yogabugrealestate.com",
    "phone": null,
    "brokerage": "YOGABUG REAL ESTATE LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Sherry Francis",
    "email": "sherry@sfgteam.com",
    "phone": null,
    "brokerage": "Eleete Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Elysse Ralph",
    "email": "hello@elysseralph.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Tracey Henkels",
    "email": "tracey@rootedrealtypdx.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Kaleb Bird-Kinsey",
    "email": "kalebbird02@gmail.com",
    "phone": null,
    "brokerage": "SUPREME REALTY GROUP, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Christine Bonner",
    "email": "chris@chrisbonner.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Jesse Udom",
    "email": "jesse@503broker.com",
    "phone": null,
    "brokerage": "Jesse Udom Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Michelle Palmquist",
    "email": "michelle.palmquist@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "PORTLAND"
  },
  {
    "name": "Julie Galaski",
    "email": "juliegalaski@gmail.com",
    "phone": null,
    "brokerage": "Julie Galaski Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Wally Tesfa",
    "email": "wtesfa1@comcast.net",
    "phone": null,
    "brokerage": "ACQUIRE PROPERTIES",
    "city": "PORTLAND"
  },
  {
    "name": "Patrick Parks",
    "email": "patrickparks67@hotmail.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "SAINT HELENS"
  },
  {
    "name": "Mark Shadrin",
    "email": "markshadrin@bhhsnwrep.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Real Estate Professionals",
    "city": "SALEM"
  },
  {
    "name": "Christine Folz",
    "email": "christinefolzre@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "SALEM"
  },
  {
    "name": "Jonathan Minerick",
    "email": "info@homecoin.com",
    "phone": null,
    "brokerage": "HOMECOIN.COM",
    "city": "SAN DIEGO"
  },
  {
    "name": "Emily Corning",
    "email": "emily@hustlehearthomes.com",
    "phone": null,
    "brokerage": "Hustle & Heart Homes",
    "city": "SHERWOOD"
  },
  {
    "name": "Tammie Crane",
    "email": "tammie@homesbycrane.com",
    "phone": null,
    "brokerage": "HOMES BY CRANE",
    "city": "SHERWOOD"
  },
  {
    "name": "Chad Hohman",
    "email": "chadhohman@gmail.com",
    "phone": null,
    "brokerage": "HomeTown Realty",
    "city": "SILVERTON"
  },
  {
    "name": "David Schiedler",
    "email": "sdavidrgi@gmail.com",
    "phone": null,
    "brokerage": "Silverado Properties LLC",
    "city": "SUBLIMITY"
  },
  {
    "name": "Matthew McCarthy",
    "email": "matthew@ihomeoregon.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "TROUTDALE"
  },
  {
    "name": "Armando Gonzales",
    "email": "armando.gonzales@lgihomes.com",
    "phone": null,
    "brokerage": "LGI Homes - Oregon, LLC",
    "city": "VANCOUVER"
  },
  {
    "name": "Elise Campbell",
    "email": "elise@elisecampbell.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "VANCOUVER"
  },
  {
    "name": "Thomas Cotter",
    "email": "tomcotterpdx@gmail.com",
    "phone": null,
    "brokerage": "FERN RIDGE REALTY",
    "city": "VENETA"
  },
  {
    "name": "Tim Plagman",
    "email": "tim4realestate@gmail.com",
    "phone": null,
    "brokerage": "Knipe Realty ERA Powered",
    "city": "WASHOUGAL"
  },
  {
    "name": "Josh Reiter",
    "email": "jr@byjosh.com",
    "phone": null,
    "brokerage": "Josh Reiter Real Estate",
    "city": "WILSONVILLE"
  },
  {
    "name": "Rachel Delavan",
    "email": "racheledelavan@gmail.com",
    "phone": null,
    "brokerage": "Delavan Realty Inc.",
    "city": "WILSONVILLE"
  },
  {
    "name": "Alicia Dart",
    "email": "homes@bobbiandalicia.com",
    "phone": null,
    "brokerage": "SOLDERA PROPERTIES, INC.",
    "city": "WILSONVILLE"
  },
  {
    "name": "Jessica Dornin",
    "email": "jessicadornin@gmail.com",
    "phone": null,
    "brokerage": "TOTEM Properties, LLC",
    "city": "ASTORIA"
  },
  {
    "name": "Andrea Mazzarella",
    "email": "realty@andreamazz.com",
    "phone": null,
    "brokerage": "FATHOM REALTY OREGON, LLC",
    "city": "ASTORIA"
  },
  {
    "name": "Caily Plant",
    "email": "cailyplant@gmail.com",
    "phone": null,
    "brokerage": "TOTEM Properties, LLC",
    "city": "ASTORIA"
  },
  {
    "name": "Faith Bailey",
    "email": "agent.faithbailey@gmail.com",
    "phone": null,
    "brokerage": "KELLER WILLIAMS SUNSET CORRIDOR",
    "city": "ASTORIA"
  },
  {
    "name": "Kaytee Binns",
    "email": "kayteeb@kw.com",
    "phone": null,
    "brokerage": "Keller Williams Premier Partners",
    "city": "BATTLE GROUND"
  },
  {
    "name": "Hayley Geiss-Krushe",
    "email": "hayley@varsityoregon.com",
    "phone": "701-527-4077",
    "brokerage": "VARSITY REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Christi Pavia",
    "email": "christi@stellarnw.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Moria Belsey",
    "email": "moria@hcoastrealty.com",
    "phone": "503-812-9735",
    "brokerage": "Harcourts Coast Realty",
    "city": "CLOVERDALE"
  },
  {
    "name": "Jessica Webber",
    "email": "joey@timberjoey.com",
    "phone": null,
    "brokerage": "ADVANCED PROPERTY MGMT LLC",
    "city": "COOS BAY"
  },
  {
    "name": "Darci Porter",
    "email": "darciporter23@gmail.com",
    "phone": null,
    "brokerage": "EMERALD COAST REALTY",
    "city": "DEPOE BAY"
  },
  {
    "name": "Anita Quilici",
    "email": "anitarealestate@gmail.com",
    "phone": null,
    "brokerage": "EMERALD COAST REALTY",
    "city": "DEPOE BAY"
  },
  {
    "name": "Amy Plechaty",
    "email": "whalecoveamy@gmail.com",
    "phone": null,
    "brokerage": "EMERALD COAST REALTY",
    "city": "DEPOE BAY"
  },
  {
    "name": "Donald Leek",
    "email": "donaldleek22@gmail.com",
    "phone": null,
    "brokerage": "GREAT WESTERN REAL ESTATE COMPANY",
    "city": "GLENEDEN BEACH"
  },
  {
    "name": "Paul Mitchell",
    "email": "paulmitchell1realtor@gmail.com",
    "phone": null,
    "brokerage": "SOWINS REAL ESTATE & PROPERTY MANAGEMENT, LLC",
    "city": "HAMMOND"
  },
  {
    "name": "Sean Corbett",
    "email": "scorbett341@gmail.com",
    "phone": "949-244-8763",
    "brokerage": "Taylor & Taylor Realty Co",
    "city": "LINCOLN CITY"
  },
  {
    "name": "Judith Vial",
    "email": "judy.vial@outlook.com",
    "phone": null,
    "brokerage": "Taylor & Taylor Realty Co",
    "city": "LINCOLN CITY"
  },
  {
    "name": "Elena Tasker",
    "email": "elena@shorepineproperties.com",
    "phone": null,
    "brokerage": "CENTURY 21 SHOREPINE PROPERTIES",
    "city": "NESKOWIN"
  },
  {
    "name": "Michelle Bernard",
    "email": "mb@shorepineproperties.com",
    "phone": null,
    "brokerage": "CENTURY 21 SHOREPINE PROPERTIES",
    "city": "PACIFIC CITY"
  },
  {
    "name": "Kelly Monfort",
    "email": "kellymonforthomes@gmail.com",
    "phone": null,
    "brokerage": "Keller Williams Premier Partners",
    "city": "PORLTAND"
  },
  {
    "name": "Denise Wyatt",
    "email": "denisew@pahlischrealestate.com",
    "phone": "541-408-6007",
    "brokerage": "Pahlisch Real Estate, Inc.",
    "city": "POWELL BUTTE"
  },
  {
    "name": "Sheena York",
    "email": "sheena@signetrealtygroup.com",
    "phone": null,
    "brokerage": "Signet Realty",
    "city": "PRINEVILLE"
  },
  {
    "name": "Armando Solano-Lopez",
    "email": "armandostransactions1@gmail.com",
    "phone": null,
    "brokerage": "HARCOURTS ELITE",
    "city": "SALEM"
  },
  {
    "name": "Victoria Strauss",
    "email": "vickistraussbroker@gmail.com",
    "phone": null,
    "brokerage": "Martek Real Estate",
    "city": "SOUTH BEACH"
  },
  {
    "name": "Elise Jordan",
    "email": "elise@advantagerealestate.com",
    "phone": null,
    "brokerage": "ADVANTAGE REAL ESTATE",
    "city": "SOUTH BEACH"
  },
  {
    "name": "Katherine KIER",
    "email": "scarlett@advantagerealestate.com",
    "phone": null,
    "brokerage": "ADVANTAGE REAL ESTATE",
    "city": "TIDEWATER"
  },
  {
    "name": "Michael Burkhard",
    "email": "burkhardmike@gmail.com",
    "phone": null,
    "brokerage": "Martek Real Estate",
    "city": "TOLEDO"
  },
  {
    "name": "Kristi Cline",
    "email": "kristicline@rogatb.com",
    "phone": null,
    "brokerage": "Realty One Group - At The Beach",
    "city": "TOLEDO"
  },
  {
    "name": "Grace Schomus",
    "email": "localrealtorgrace@gmail.com",
    "phone": null,
    "brokerage": "Windermere Heritage",
    "city": "VANCOUVER"
  },
  {
    "name": "Iana Cherkashova",
    "email": "yanakisilev@kw.com",
    "phone": null,
    "brokerage": "Keller Williams Premier Partners",
    "city": "VANCOUVER"
  },
  {
    "name": "Brandon Fox",
    "email": "kyle@foxrealestategroups.com",
    "phone": null,
    "brokerage": "Keller Williams Premier Partners",
    "city": "VANCOUVER"
  },
  {
    "name": "Mac Creasman",
    "email": "macbroker1@gmail.com",
    "phone": null,
    "brokerage": "EMERALD COAST REALTY",
    "city": "YACHATS"
  },
  {
    "name": "Tiffanie Danley",
    "email": "tiffanie@tdrealtygroup.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEAVERTON"
  },
  {
    "name": "Dorothea Chakos",
    "email": "dchakos@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "BEAVERTON"
  },
  {
    "name": "Erin Monahan",
    "email": "erin@hellohomebyerin.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "BEAVERTON"
  },
  {
    "name": "Kimberly Motto",
    "email": "kimberlymotto@mac.com",
    "phone": null,
    "brokerage": "CALL IT CLOSED INTERNATIONAL, INC",
    "city": "BEAVERTON"
  },
  {
    "name": "Janae Olsen",
    "email": "lovewhereyoulivenw@gmail.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "BEAVERTON"
  },
  {
    "name": "Rolf Selbeck",
    "email": "rselbeck@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "BEAVERTON"
  },
  {
    "name": "Shannon Goyne",
    "email": "shannongoynerealtor@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEAVERTON"
  },
  {
    "name": "Cynthia Fneish",
    "email": "cynthiafneish@gmail.com",
    "phone": null,
    "brokerage": "Weichert Realtors(r) on Main Street",
    "city": "BEAVERTON"
  },
  {
    "name": "Jennifer Redd",
    "email": "jenn.redd@varsityoregon.com",
    "phone": null,
    "brokerage": "VARSITY REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Carol Tobey",
    "email": "caroltobeyrealtor@gmail.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Jason Curran",
    "email": "jason@thegarnergroup.com",
    "phone": "541-639-6075",
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Jennifer Swain",
    "email": "jennajrealestate@gmail.com",
    "phone": null,
    "brokerage": "NINEBARK REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Angelica Webb",
    "email": "angelica.webb@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "BEND"
  },
  {
    "name": "Charles Burchfield",
    "email": "randy@randyburchfield.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Canon Caruso",
    "email": "flashycanon@gmail.com",
    "phone": "541-410-7981",
    "brokerage": "EXP REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "George Riggins",
    "email": "griggins@bhhsnw.com",
    "phone": null,
    "brokerage": "1 Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "BEND"
  },
  {
    "name": "Shelby Steele",
    "email": "shelbykine@gmail.com",
    "phone": "541-848-2079",
    "brokerage": "KINE AND KINE PROPERTIES",
    "city": "BEND"
  },
  {
    "name": "Mariah Luelling",
    "email": "mariah@luellingteam.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Ryan Luelling",
    "email": "ryan@luellingteam.com",
    "phone": "541-419-4883",
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Kimberly Morse",
    "email": "kimberly@sgbend.com",
    "phone": "970-275-8470",
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "Kathleen Lang",
    "email": "kathy@thegarnergroup.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Kimberly Bishop",
    "email": "kbishoporegonhomes@gmail.com",
    "phone": null,
    "brokerage": "Engel & Voelkers Bend",
    "city": "BEND"
  },
  {
    "name": "Vincent Bishop",
    "email": "vbishoporegonhomes@gmail.com",
    "phone": "541-410-8685",
    "brokerage": "Engel & Voelkers Bend",
    "city": "BEND"
  },
  {
    "name": "Mark Cain",
    "email": "cainrealestate@outlook.com",
    "phone": "541-740-8691",
    "brokerage": "The Cain Company LLC",
    "city": "BEND"
  },
  {
    "name": "Deborah Latham",
    "email": "debglat@gmail.com",
    "phone": null,
    "brokerage": "CENTURY 21 NORTH HOMES REALTY",
    "city": "BEND"
  },
  {
    "name": "Katrina Swisher",
    "email": "katrina@bendhomeguide.com",
    "phone": "541-382-8262",
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "Ryan Endries",
    "email": "ryan@dukewarner.com",
    "phone": null,
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "Leslie Wegmet",
    "email": "wegmetrealestate@gmail.com",
    "phone": "541-527-2030",
    "brokerage": "1 Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "BEND"
  },
  {
    "name": "Kelsey Kelley",
    "email": "kelsey.kelley@gmail.com",
    "phone": null,
    "brokerage": "SHELTON D. KELLEY REALTY",
    "city": "BEND"
  },
  {
    "name": "Jessica Ardeljan",
    "email": "jessica.ardeljan@gmail.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Amanda Ferrari",
    "email": "amanda@dukewarner.com",
    "phone": null,
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "David Quinney",
    "email": "dj@dukewarner.com",
    "phone": "541-213-8026",
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "Brook Criazzo",
    "email": "brookcriazzo@gmail.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Kris Cavin",
    "email": "kcavin@hayden-homes.com",
    "phone": "541-640-6292",
    "brokerage": "New Home Star Oregon, LLC",
    "city": "BEND"
  },
  {
    "name": "Erin Lovelace",
    "email": "erinlovelacerealty@gmail.com",
    "phone": null,
    "brokerage": "Knipe Realty ERA Powered",
    "city": "BEND"
  },
  {
    "name": "Taylor GeDeros",
    "email": "taylorgrealestate@outlook.com",
    "phone": null,
    "brokerage": "Knipe Realty ERA Powered",
    "city": "BEND"
  },
  {
    "name": "James Vinciguerra",
    "email": "james.vinciguerra@gmail.com",
    "phone": null,
    "brokerage": "Lennar Sales Corp",
    "city": "BEND"
  },
  {
    "name": "Julia Gehring",
    "email": "julia@stellarnw.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Alexandria Bolden",
    "email": "bolden.alexandria@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEND"
  },
  {
    "name": "Fred Johnson",
    "email": "fred@dukewarner.com",
    "phone": null,
    "brokerage": "DUKE WARNER REALTY ERA POWERED",
    "city": "BEND"
  },
  {
    "name": "Haley Overton",
    "email": "haley.overton@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEND"
  },
  {
    "name": "Kristan Folden",
    "email": "kristan@varsityoregon.com",
    "phone": null,
    "brokerage": "VARSITY REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Jill Wheeler",
    "email": "jillkwheeler@gmail.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Connie Mitchell",
    "email": "connie@teamstellarnw.com",
    "phone": null,
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Gregory Broderick",
    "email": "greg@bendrealestate.com",
    "phone": "541-280-2363",
    "brokerage": "STELLAR REALTY NORTHWEST",
    "city": "BEND"
  },
  {
    "name": "Angelina Guier",
    "email": "angie.guier.realtor@gmail.com",
    "phone": "541-749-7670",
    "brokerage": "Keller Williams Realty Central Oregon",
    "city": "BEND"
  },
  {
    "name": "Paul Streichan",
    "email": "paul@lohrgroup.pro",
    "phone": "541-233-6130",
    "brokerage": "EPIQUE REALTY",
    "city": "BEND"
  },
  {
    "name": "Vonnie Green",
    "email": "vonniegreen@msn.com",
    "phone": null,
    "brokerage": "ALLEDA REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Dennis Doi",
    "email": "dennis.doi@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEND"
  },
  {
    "name": "Linda Spittler",
    "email": "lindas@pahlischrealestate.com",
    "phone": null,
    "brokerage": "Pahlisch Real Estate, Inc.",
    "city": "BEND"
  },
  {
    "name": "Sofia Pouget-Prieto",
    "email": "sofia@teammcglone.com",
    "phone": "541-848-0290",
    "brokerage": "EXP REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "Molly Sommer",
    "email": "mollyjo@thegarnergroup.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Rosann Garza",
    "email": "rosann@highdesertrealty.com",
    "phone": "510-460-5058",
    "brokerage": "HIGH DESERT REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "Katharyn Pollock",
    "email": "katy@krommrealestate.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEND"
  },
  {
    "name": "Cole Billings",
    "email": "cole@varsityoregon.com",
    "phone": null,
    "brokerage": "VARSITY REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Kenneth Morgan",
    "email": "ken@morgansclassicconstruction.com",
    "phone": "541-231-5712",
    "brokerage": "NINEBARK REAL ESTATE",
    "city": "BEND"
  },
  {
    "name": "Brandee Remley",
    "email": "brandeeremley@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BEND"
  },
  {
    "name": "Alison Mata",
    "email": "alison@thegarnergroup.com",
    "phone": null,
    "brokerage": "Harcourts The Garner Group Real Estate",
    "city": "BEND"
  },
  {
    "name": "Mary Bartholomew",
    "email": "marybartholomew79@gmail.com",
    "phone": null,
    "brokerage": "Knipe Realty ERA Powered",
    "city": "BEND"
  },
  {
    "name": "Alice Fairbairn",
    "email": "bendrealestateservices@gmail.com",
    "phone": "541-921-1292",
    "brokerage": "EXP REALTY, LLC",
    "city": "BEND"
  },
  {
    "name": "Carrie Sorem",
    "email": "brokersorem@gmail.com",
    "phone": "541-279-3775",
    "brokerage": "C O Properties Inc",
    "city": "BEND"
  },
  {
    "name": "Kimberlee Elbel",
    "email": "kimelbelrealtor@gmail.com",
    "phone": null,
    "brokerage": "COCHRAN PROPERTY GROUP, INC.",
    "city": "BORING"
  },
  {
    "name": "Alyssa Hunter",
    "email": "alyssahunter407@gmail.com",
    "phone": null,
    "brokerage": "All County Real Estate",
    "city": "BORING"
  },
  {
    "name": "Cassandra Marks",
    "email": "cassandra@realtorcas.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "BRUSH PRAIRIE"
  },
  {
    "name": "Brian Thompson",
    "email": "brianthompson@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "BRUSH PRAIRIE"
  },
  {
    "name": "Sang Vu",
    "email": "sang@rarebirdrealestate.com",
    "phone": null,
    "brokerage": "RareBird Real Estate",
    "city": "CAMAS"
  },
  {
    "name": "Emily Handris",
    "email": "emily@iconconstruction.net",
    "phone": null,
    "brokerage": "THE HANDRIS REALTY CO.",
    "city": "CANBY"
  },
  {
    "name": "Kristi Calcagno",
    "email": "kristi@cochranpropertygroup.com",
    "phone": null,
    "brokerage": "COCHRAN PROPERTY GROUP, INC.",
    "city": "CARLSBAD"
  },
  {
    "name": "Chase D'Ambrosio",
    "email": "chasedambrosio1@gmail.com",
    "phone": null,
    "brokerage": "Real Estate Performance Group LLC",
    "city": "CLACKAMAS"
  },
  {
    "name": "Carie Serrano",
    "email": "carieserrano1@gmail.com",
    "phone": null,
    "brokerage": "CHECK POINT REALTY, LLC",
    "city": "CLACKAMAS"
  },
  {
    "name": "Kayla Linscott",
    "email": "kayla@equityoregon.com",
    "phone": null,
    "brokerage": "EQUITY OREGON REAL ESTATE",
    "city": "CLACKAMAS"
  },
  {
    "name": "Ryan Bak",
    "email": "ryan@teambak.com",
    "phone": "860-817-7036",
    "brokerage": "Knightsbridge International Real Estate, LLC",
    "city": "CRESTED BUTTE"
  },
  {
    "name": "Bailey Savage",
    "email": "baileysavage2002@gmail.com",
    "phone": "971-599-9091",
    "brokerage": "CENTURY 21 SHOREPINE PROPERTIES",
    "city": "DALLAS"
  },
  {
    "name": "Janice Lundy",
    "email": "jlundy@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "ESTACADA"
  },
  {
    "name": "Tanner Stottlemyre",
    "email": "tjstottlemyre@drhorton.com",
    "phone": "541-270-0725",
    "brokerage": "D. R. HORTON, INC. - PORTLAND",
    "city": "EUGENE"
  },
  {
    "name": "Selina Klein",
    "email": "selina@kellymarketinggroup.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "FAIRVIEW"
  },
  {
    "name": "Brian Fulsher",
    "email": "brian@fulsherrealestate.com",
    "phone": null,
    "brokerage": "MAL & SEITZ",
    "city": "FAIRVIEW"
  },
  {
    "name": "Matt Ralphe",
    "email": "mralphe79@gmail.com",
    "phone": null,
    "brokerage": "TREEHOUSE REALTY, LLC.",
    "city": "FOREST GROVE"
  },
  {
    "name": "Morgan Braze",
    "email": "morganbraze@gmail.com",
    "phone": null,
    "brokerage": "Kelly Right Real Estate of Portland LLC",
    "city": "FOREST GROVE"
  },
  {
    "name": "Marissa Newbury",
    "email": "marissa@marissanewbury.com",
    "phone": null,
    "brokerage": "EQUITY OREGON REAL ESTATE",
    "city": "GOVERNMENT CAMP"
  },
  {
    "name": "Laura Allen",
    "email": "laura.allen@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "GRAND RONDE"
  },
  {
    "name": "Douglas Carrillo",
    "email": "doug@brantleychristianson.com",
    "phone": null,
    "brokerage": "Brantley Christianson Real Estate PLLC",
    "city": "GRESHAM"
  },
  {
    "name": "Melissa Wicks",
    "email": "melissa@theregergroupnetwork.com",
    "phone": null,
    "brokerage": "REGER HOMES, LLC",
    "city": "HAPPY VALLEY"
  },
  {
    "name": "Derek Oliver",
    "email": "derek@olivernwrealestate.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "HAPPY VALLEY"
  },
  {
    "name": "Rosemary Coles",
    "email": "rosemary.coles@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "HAPPY VALLEY"
  },
  {
    "name": "Chunjuan Ye",
    "email": "jane@brantleychristianson.com",
    "phone": null,
    "brokerage": "Brantley Christianson Real Estate PLLC",
    "city": "HAPPY VALLEY"
  },
  {
    "name": "Heather Quirke",
    "email": "hquirke@drhorton.com",
    "phone": null,
    "brokerage": "D. R. HORTON, INC. - PORTLAND",
    "city": "HILLSBORO"
  },
  {
    "name": "Michael Benson",
    "email": "michaelbenson@johnlscott.com",
    "phone": null,
    "brokerage": "JOHN L SCOTT",
    "city": "LA CENTER"
  },
  {
    "name": "Lacie Pech",
    "email": "realtywithlacie@gmail.com",
    "phone": "541-604-9630",
    "brokerage": "Knipe Realty ERA Powered",
    "city": "LA PINE"
  },
  {
    "name": "Michael Beirwagen",
    "email": "mbeirwagen@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Mark Popkin",
    "email": "mark@popkinre.com",
    "phone": null,
    "brokerage": "POPKIN REAL ESTATE, LLC",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Mendi Mei",
    "email": "mendi.mei@pulte.com",
    "phone": null,
    "brokerage": "PULTE HOMES OF OREGON, INC.",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Susan Stohl",
    "email": "susan.stohl@eleetere.com",
    "phone": null,
    "brokerage": "Eleete Real Estate",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Lynda O'neill",
    "email": "lyndao@johnlscott.com",
    "phone": null,
    "brokerage": "JOHN L SCOTT",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Jennifer Weinhart",
    "email": "jennifer.weinhart@theagencyre.com",
    "phone": null,
    "brokerage": "THE AGENCY PORTLAND",
    "city": "LAKE OSWEGO"
  },
  {
    "name": "Nixon Leon",
    "email": "nleon.cec@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "LAS VEGAS"
  },
  {
    "name": "Mackenzie Licea",
    "email": "mackenzie@yourscoutrealty.com",
    "phone": null,
    "brokerage": "SCOUT REALTY LLC",
    "city": "MADRAS"
  },
  {
    "name": "Tricia Hansen",
    "email": "trish@trealty.me",
    "phone": null,
    "brokerage": "Engel & Voelkers Bend",
    "city": "MADRAS"
  },
  {
    "name": "William Murphy",
    "email": "willmurphyrealtor@gmail.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "MAYWOOD PARK"
  },
  {
    "name": "Kathryn Heydel",
    "email": "kathyheydel@c21nhr.com",
    "phone": null,
    "brokerage": "CENTURY 21 NORTH HOMES REALTY",
    "city": "MILWAUKIE"
  },
  {
    "name": "Bryce Rosenbaum",
    "email": "bryce@brycerosenbaum.com",
    "phone": null,
    "brokerage": "Harcourts Real Estate Network Group",
    "city": "MILWAUKIE"
  },
  {
    "name": "Rosalie Herboth",
    "email": "herbothhomesllc@gmail.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "MILWAUKIE"
  },
  {
    "name": "Natalya Oreste",
    "email": "noreste@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "MILWAUKIE"
  },
  {
    "name": "Hunde Abebe",
    "email": "hunde@advantageor.com",
    "phone": null,
    "brokerage": "Advantage Realty, LLC",
    "city": "MILWAUKIE"
  },
  {
    "name": "Travis Hinkle",
    "email": "travishinkle.01@gmail.com",
    "phone": null,
    "brokerage": "CHANGE REALTY, LLC",
    "city": "OREGON CITY"
  },
  {
    "name": "Mike Day",
    "email": "mikedsellshouses@gmail.com",
    "phone": null,
    "brokerage": "HOMESOURCE",
    "city": "OREGON CITY"
  },
  {
    "name": "Natalie Schirm-Olson",
    "email": "natalie@pnwbroker.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Jeanne Tunberg",
    "email": "jeanne.tunberg@gmail.com",
    "phone": null,
    "brokerage": "PROUD REALTY LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Sharon Parmenter",
    "email": "sparmenter@opendoor.com",
    "phone": null,
    "brokerage": "OPENDOOR BROKERAGE LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Sarfraz Ahmed",
    "email": "steveshomes@gmail.com",
    "phone": null,
    "brokerage": "Knipe Realty ERA Powered",
    "city": "PORTLAND"
  },
  {
    "name": "Alicia Selliken",
    "email": "alicia.selliken@gmail.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Emily Michel",
    "email": "pdxgreenteam@gmail.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Rome Mortera",
    "email": "rmortera@kellyright.com",
    "phone": null,
    "brokerage": "Kelly Right Real Estate of Portland LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Jason Gill",
    "email": "jasongill@premierepropertygroup.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Lily Wyss",
    "email": "lily@lilyrayres.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Patricia LoCascio",
    "email": "patricia@bridgetoportland.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Samirah Akbari-Mort",
    "email": "sami@lovejoyrealestate.com",
    "phone": null,
    "brokerage": "Lovejoy Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Marissa Sainz",
    "email": "marissa@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Bryan Durk",
    "email": "bryankd@mac.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "PORTLAND"
  },
  {
    "name": "Kimberly Woodhouse",
    "email": "kim@kimwoodhousepdx.com",
    "phone": null,
    "brokerage": "SOLDERA PROPERTIES, INC.",
    "city": "PORTLAND"
  },
  {
    "name": "Tai Faux",
    "email": "tai@hausfraupnw.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Holly Rodriguez",
    "email": "holly.rodriguez@theagencyre.com",
    "phone": null,
    "brokerage": "THE AGENCY PORTLAND",
    "city": "PORTLAND"
  },
  {
    "name": "Stephanie Soden",
    "email": "pdxsoden@gmail.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "William Grzebyk",
    "email": "william.grzebyk@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "PORTLAND"
  },
  {
    "name": "Aaron Rader",
    "email": "aaron.rader@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "PORTLAND"
  },
  {
    "name": "Heidi Hopfer",
    "email": "heidi@heidipdx.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "James Lerman",
    "email": "jimlerman@epique.me",
    "phone": null,
    "brokerage": "EPIQUE REALTY",
    "city": "PORTLAND"
  },
  {
    "name": "Erin Wetherbee",
    "email": "erin@wetherbeehomes.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Erica Goodfriend",
    "email": "egoodfriendrealtor@gmail.com",
    "phone": null,
    "brokerage": "VETIVER STREET",
    "city": "PORTLAND"
  },
  {
    "name": "Alexander Ney",
    "email": "alex@urbannestpdx.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Olivia Rush",
    "email": "oliviarushpdx@gmail.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Alia Hazen",
    "email": "alia.hazen@gmail.com",
    "phone": null,
    "brokerage": "THE AGENCY PORTLAND",
    "city": "PORTLAND"
  },
  {
    "name": "Luis Solis",
    "email": "luis@luissolisrealty.com",
    "phone": null,
    "brokerage": "HomeSmart Realty Group",
    "city": "PORTLAND"
  },
  {
    "name": "Jacob Serrill",
    "email": "jacobserrill@gmail.com",
    "phone": null,
    "brokerage": "Kelly Right Real Estate of Portland LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Erika George",
    "email": "team@houselovepdx.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Iraida Hermann",
    "email": "ibhermann@bhhsnw.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Shannon McLaughlin",
    "email": "homes@shanonym.com",
    "phone": null,
    "brokerage": "PROUD REALTY LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Joseph Dressman",
    "email": "joedressman@gmail.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Shane Morgan",
    "email": "shanemorganpdx@gmail.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Ella Gray",
    "email": "ella@ellagrayre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Carolyn Groves",
    "email": "carolyn@urbannestpdx.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Megan Feil",
    "email": "megan@meganfeil.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Jett Even",
    "email": "jett@floatingoregonhomes.com",
    "phone": null,
    "brokerage": "SIMPLIHOM OREGON LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Carolyn Spurlock",
    "email": "carrie@spurlockco.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "David Backholer",
    "email": "david@pdxhomerealty.com",
    "phone": null,
    "brokerage": "Premiere Real Estate Professionals, LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Sean O'Feery",
    "email": "sean@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Julie Williamson",
    "email": "julesyourrealtor@gmail.com",
    "phone": null,
    "brokerage": "Realty One Group Prestige",
    "city": "PORTLAND"
  },
  {
    "name": "Lauren Hurley",
    "email": "lauren@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Elizabeth Nathan",
    "email": "elizabethnathan@urbannestpdx.com",
    "phone": null,
    "brokerage": "Urban Nest Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Savanna Ray",
    "email": "savanna@grandcruproperties.com",
    "phone": null,
    "brokerage": "THE AGENCY PORTLAND",
    "city": "PORTLAND"
  },
  {
    "name": "Todd Peres",
    "email": "todd@debbiethomas.com",
    "phone": null,
    "brokerage": "DEBBIE THOMAS REAL ESTATE",
    "city": "PORTLAND"
  },
  {
    "name": "Kelsey Burkett",
    "email": "kelsey@rootedrealtypdx.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Whitney Parker",
    "email": "whitney.parker@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "PORTLAND"
  },
  {
    "name": "Rio Palomares",
    "email": "howdy@wranglingrio.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Susanne Watzig",
    "email": "homesbysusanne@gmail.com",
    "phone": null,
    "brokerage": "INTEGRITY HOME REALTY LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Rachel Cardman-Brewer",
    "email": "rachelcb@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Nicolette Hanna",
    "email": "nicolette@nicolettehannarealestate.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Deanna Cintas",
    "email": "deannacintasrealestate@gmail.com",
    "phone": null,
    "brokerage": "PROUD REALTY LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Nicole Gardner",
    "email": "nikki@nikkigardner.com",
    "phone": null,
    "brokerage": "Eleete Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Noel Jackson",
    "email": "noel@jacksonhart.com",
    "phone": null,
    "brokerage": "THE AGENCY PORTLAND",
    "city": "PORTLAND"
  },
  {
    "name": "Dulcinea Myers-Newcomb",
    "email": "dulcinea@livingroomre.com",
    "phone": null,
    "brokerage": "Living Room Realty",
    "city": "PORTLAND"
  },
  {
    "name": "Alina Aliyar",
    "email": "alina@livingroomre.com",
    "phone": null,
    "brokerage": "Neighbors Realty LLC",
    "city": "PORTLAND"
  },
  {
    "name": "Elisabeth Lynn",
    "email": "elizlynn@msn.com",
    "phone": null,
    "brokerage": "Think Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Elisha Alcantara",
    "email": "elisha@elishaalcantara.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "PORTLAND"
  },
  {
    "name": "Christopher Rowley",
    "email": "christopher.rowley@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "PORTLAND"
  },
  {
    "name": "Jarrin Benson",
    "email": "jarrin@jarrinbenson.com",
    "phone": null,
    "brokerage": "KELLER WILLIAMS REALTY, PORTLAND CENTRAL",
    "city": "PORTLAND"
  },
  {
    "name": "Justin Dolinger",
    "email": "jdolinger@gmail.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "PORTLAND"
  },
  {
    "name": "Amy Wakefield",
    "email": "amy@movingtoeaglecrest.com",
    "phone": "541-513-0444",
    "brokerage": "EAGLE CREST PROPERTIES",
    "city": "REDMOND"
  },
  {
    "name": "Oksana Tsarenko",
    "email": "realtoroksana@gmail.com",
    "phone": null,
    "brokerage": "KELLER WILLIAMS REALTY PORTLAND PREMIERE",
    "city": "RIDGEFIELD"
  },
  {
    "name": "Gregory Rider",
    "email": "gregory@riderrealestatenw.com",
    "phone": null,
    "brokerage": "JOHN L SCOTT",
    "city": "RIDGEFIELD"
  },
  {
    "name": "Sarah Hedal",
    "email": "hedalhomes@gmail.com",
    "phone": null,
    "brokerage": "SIMPLIHOM OREGON LLC",
    "city": "SALEM"
  },
  {
    "name": "Cristian Martinez",
    "email": "cristian.martinez@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "SALEM"
  },
  {
    "name": "Kimberly Gray",
    "email": "kimberlygray@homestarbrokers.com",
    "phone": null,
    "brokerage": "HOMESTAR BROKERS, LLC",
    "city": "SALEM"
  },
  {
    "name": "Suzanne Scott",
    "email": "suzanne@scottholdings.org",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "SANDY"
  },
  {
    "name": "Jonathan Schweitzer",
    "email": "jonathan.schweitzer@redfin.com",
    "phone": null,
    "brokerage": "Redfin",
    "city": "SANDY"
  },
  {
    "name": "Gigi Duncan",
    "email": "gigiduncanhome@gmail.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "SANDY"
  },
  {
    "name": "Jennifer Parral",
    "email": "parraljen@gmail.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "SCAPPOOSE"
  },
  {
    "name": "Kylie Haren",
    "email": "kylie@hustlehearthomes.com",
    "phone": null,
    "brokerage": "Hustle & Heart Homes",
    "city": "SHERWOOD"
  },
  {
    "name": "Ryan Kelly",
    "email": "ryan.kelly@whitetailproperties.com",
    "phone": null,
    "brokerage": "WHITETAIL PROPERTIES REAL ESTATE, LLC",
    "city": "SPRINGFIELD"
  },
  {
    "name": "Kris Reed",
    "email": "kris@hearthstonere.com",
    "phone": null,
    "brokerage": "HEARTHSTONE REAL ESTATE",
    "city": "SPRINGFIELD"
  },
  {
    "name": "Kirsten Burt",
    "email": "kirstenburt9@gmail.com",
    "phone": null,
    "brokerage": "Copper Tree Realty, LLC",
    "city": "SUBLIMITY"
  },
  {
    "name": "William Florence",
    "email": "willflorencerealtor@gmail.com",
    "phone": null,
    "brokerage": "Knightsbridge International Real Estate, LLC",
    "city": "TERREBONNE"
  },
  {
    "name": "Patricia Spreen",
    "email": "patti.spreen@gmail.com",
    "phone": null,
    "brokerage": "OREGON FIRST",
    "city": "TIGARD"
  },
  {
    "name": "Michelle Schock",
    "email": "mschock66@gmail.com",
    "phone": null,
    "brokerage": "CENTURY 21 Northstar",
    "city": "TIGARD"
  },
  {
    "name": "Peter Cutile",
    "email": "peter@petercutile.com",
    "phone": null,
    "brokerage": "MODERN REALTY",
    "city": "VANCOUVER"
  },
  {
    "name": "Marina Golovatii",
    "email": "marina@cityviberealty.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "VANCOUVER"
  },
  {
    "name": "Anthony Pitre",
    "email": "anthony@antpitre.com",
    "phone": null,
    "brokerage": "LIMBRICK REAL ESTATE GROUP",
    "city": "VANCOUVER"
  },
  {
    "name": "Steve Milford",
    "email": "steve@stevemilfordrealtor.com",
    "phone": null,
    "brokerage": "Kelly Right Real Estate of Portland LLC",
    "city": "VANCOUVER"
  },
  {
    "name": "Mark Warmanen",
    "email": "mark@hittingthemark.com",
    "phone": null,
    "brokerage": "Berkshire Hathaway HomeServices Northwest Real Estate",
    "city": "WILSONVILLE"
  },
  {
    "name": "Victoria Marquez",
    "email": "vicki@vickimarquezhomes.com",
    "phone": null,
    "brokerage": "PREMIERE PROPERTY GROUP, LLC",
    "city": "WILSONVILLE"
  },
  {
    "name": "Ryan Kristin",
    "email": "ryan@ryankristinrealty.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "WILSONVILLE"
  },
  {
    "name": "Katharine Granum",
    "email": "kat@katgranum.com",
    "phone": null,
    "brokerage": "Real Broker",
    "city": "WILSONVILLE"
  }
];
