export interface Candidate {
  name: string;
  email: string;
  phone: string | null;
}

export const candidates: Candidate[] = [
  {name: "Jason Mann",email: "jaymann4210@hotmail.com",phone: "541-733-0121"},
  {name: "Lynn Johnson",email: "lynn@ivre.co",phone: null},
  {name: "Sue Kern",email: "sue@ivre.co",phone: null},
  {name: "Tonya Box",email: "tonya@ivre.co",phone: null},
  {name: "Collette Scholer",email: "collettescholer@gmail.com",phone: null},
  {name: "Corbin Duncan",email: "corbin@lanecountyrealtor.homes",phone: "541-912-7881"},
  {name: "Eric M Smith",email: "eric@lanecountyrealtor.homes",phone: "541-912-5778"},
  {name: "Kayla Pancake",email: "pancakeprorealty@gmail.com",phone: null},
  {name: "Madeline Duncan",email: "madeline@lanecountyrealtor.homes",phone: "541-556-2103"},
  {name: "Megan Naslund",email: "meganprorealty@gmail.com",phone: null},
  {name: "Miltina Scaife",email: "miltina@bossig.com",phone: "541-953-7355"},
  {name: "Cindy Griggs",email: "cgriggs@eotnet.net",phone: "541-571-1153"},
  {name: "Mike Boylan",email: "mike@boylanrealty.com",phone: "541-561-7017"},
  {name: "Chris Larsson",email: "chris@oswegorealestategroup.com",phone: null},
  {name: "Todd Branson",email: "toddbranson@yahoo.com",phone: "541-409-1800"},
  {name: "Barry House",email: "house@bakerstreetrealestate.com",phone: "971-241-0098"},
  {name: "Jen Feero",email: "jenfeero@bakerstreetrealestate.com",phone: "503-708-2658"},
  {name: "Jessica Love",email: "jessicalove@bakerstreetrealestate.com",phone: "971-237-7736"},
  {name: "Joyce Lowry",email: "joycelowry@bakerstreetrealestate.com",phone: "503-985-8677"},
  {name: "Stacy Martin",email: "stacymartin@bakerstreetrealestate.com",phone: "503-560-2144"},
  {name: "Susan Stubberfield",email: "susanstubberfield@bakerstreetrealestate.com",phone: "503-435-9274"},
  {name: "Trisha House",email: "trishahouse@bakerstreetrealestate.com",phone: "503-437-1822"},
  {name: "Colby Kielman",email: "colby@orop.com",phone: "541-531-3086"},
  {name: "Diane Major",email: "dmajor@orop.com",phone: "541-821-8699"},
  {name: "Jerry Scheffler",email: "jerrys@orop.com",phone: "541-774-4444"},
  {name: "Kim Stewart",email: "kims@orop.com",phone: "541-772-0000"},
  {name: "Lisa Arenas",email: "larenas@orop.com",phone: "541-774-4412"},
  {name: "April Halbert",email: "aprilcombie@yahoo.com",phone: null},
  {name: "Belinda Mace",email: "barnmace@msn.com",phone: null},
  {name: "Karin Hughes",email: "khughes.johnsongroup@gmail.com",phone: null},
  {name: "Ricky Ostle",email: "rickyostle.johnsongroup@gmail.com",phone: null},
  {name: "Scott Osmon",email: "scottosmonproperties@gmail.com",phone: "503-459-1623"},
  {name: "Alan Caballero",email: "alan@nedbaker.com",phone: null},
  {name: "Del Lira",email: "del@nedbaker.com",phone: null},
  {name: "Diana Pfenning",email: "diana@nedbaker.com",phone: null},
  {name: "Donna Wilson",email: "donna@nedbaker.com",phone: null},
  {name: "Hannah Thompson",email: "hannah@nedbaker.com",phone: "503-991-3099"},
  {name: "Heidi Beckett",email: "heidi@nedbaker.com",phone: null},
  {name: "Parker Reed",email: "parker@homestarbrokers.com",phone: "503-979-1835"},
  {name: "Levi Wilson",email: "levi@nedbaker.com",phone: "503-881-5286"},
  {name: "Sarah Letterman",email: "sarah@nedbaker.com",phone: null},
  {name: "Alex Meraz",email: "alexmeraz@matinrealestate.com",phone: "509-619-4099"},
  {name: "Amy Mead",email: "amymead@matinrealestate.com",phone: "503-975-1972"},
  {name: "Andy Wilcox",email: "andy@matinrealestate.com",phone: "702-561-6938"},
  {name: "Ben Fabian",email: "ben@matinrealestate.com",phone: "971-401-1071"},
  {name: "Boston Bate",email: "boston@matinrealestate.com",phone: "541-965-0159"},
  {name: "Brooklyn Nagle",email: "brooklyn@matinrealestate.com",phone: "503-502-0069"},
  {name: "Charles Corbett",email: "charles@matinrealestate.com",phone: "971-272-3218"},
  {name: "Chase Bright",email: "chase@matinrealestate.com",phone: "971-409-3237"},
  {name: "Chris Sjothun",email: "chris.s@matinrealestate.com",phone: "360-936-8658"},
  {name: "Chris Zurita",email: "chris@matinrealestate.com",phone: "971-269-8831"},
  {name: "Christopher Young",email: "christopher@matinrealestate.com",phone: "971-401-3753"},
  {name: "Damian Hill",email: "damianhill@matinrealestate.com",phone: "503-883-3420"},
  {name: "Ellen Morehead",email: "ellen@matinrealestate.com",phone: "808-429-1990"},
  {name: "Eric Leuschner",email: "eric.leuschner@matinrealestate.com",phone: "503-509-2012"},
  {name: "Erika Browne",email: "erikabrowne@matinrealestate.com",phone: "971-777-1914"},
  {name: "Erin Martin",email: "erin@matinrealestate.com",phone: "503-962-0293"},
  {name: "Finch Myburgh",email: "finch@matinrealestate.com",phone: "503-884-8453"},
  {name: "Janae Chaves",email: "janae@matinrealestate.com",phone: "503-422-7265"},
  {name: "Jason Veith",email: "jason@matinrealestate.com",phone: "832-471-9569"},
  {name: "Joe Bothe",email: "joe@matinrealestate.com",phone: "503-680-7250"},
  {name: "Jordan Matin",email: "manager@matinrealestate.com",phone: "503-622-9601"},
  {name: "Joshua Rose",email: "josh@matinrealestate.com",phone: "541-430-5755"},
  {name: "Karen Tse",email: "karen@matinrealestate.com",phone: "360-931-7825"},
  {name: "Kimberly Ilosvay",email: "kimilosvay@matinrealestate.com",phone: "971-270-6137"},
  {name: "Leona Mullen",email: "leona@matinrealestate.com",phone: "971-712-6959"},
  {name: "Lexa Brice",email: "lexa@matinrealestate.com",phone: "602-706-0546"},
  {name: "Lisa Truong",email: "lisatruong@matinrealestate.com",phone: "503-475-8842"},
  {name: "Maleigha Martinez",email: "maleigha@matinrealestate.com",phone: "971-201-6715"},
  {name: "Michelle McFadden",email: "michelle@matinrealestate.com",phone: "503-330-4020"},
  {name: "Miguel Contreras",email: "miguel@matinrealestate.com",phone: "971-275-3813"},
  {name: "Nancy Alhayek",email: "nancy@matinrealestate.com",phone: "503-841-3103"},
  {name: "Naomi Kozhokar",email: "naomi.kozhokar@matinrealestate.com",phone: "503-826-4355"},
  {name: "Nick Chamberlin",email: "nick@matinrealestate.com",phone: "971-977-1190"},
  {name: "Ocean Chau",email: "ocean@matinrealestate.com",phone: "971-221-1184"},
  {name: "Reed Bright",email: "reed@matinrealestate.com",phone: "503-927-7110"},
  {name: "Ross Steffan",email: "ross.steffan@matinrealestate.com",phone: "541-221-6878"},
  {name: "Russell Xay",email: "russell@matinrealestate.com",phone: "808-457-6933"},
  {name: "Sierra Lockwood",email: "sierra@matinrealestate.com",phone: "360-606-6284"},
  {name: "Sophia Freiling",email: "sophia@matinrealestate.com",phone: "503-858-7597"},
  {name: "Vince Kinney",email: "vince@matinrealestate.com",phone: "503-840-2627"},
  {name: "Winter DesJardins",email: "winterdesjardins@matinrealestate.com",phone: "503-929-6626"},
  {name: "Zach Hosford",email: "zach@matinrealestate.com",phone: "707-567-4608"},
  {name: "Zake Cohen",email: "zakecohen@matinrealestate.com",phone: "360-831-5325"},
  {name: "Geoff Groener",email: "geoff@emeraldcoastrealty.com",phone: "541-390-4488"},
  {name: "Ronda Woosley",email: "emeraldgirl@rondawoosley.com",phone: "541-620-4036"},
];
