export interface Candidate {
  name: string;
  email: string;
  phone: string | null;
}

export const candidates: Candidate[] = [
  { name: "Amanda Stiehl", email: "amanda@amandastiehlrealty.com", phone: "541-981-8424" },
  { name: "Carlene Hester", email: "chester@mind.net", phone: null },
  { name: "Helen Whitcomb", email: "whitcomb.helen@gmail.com", phone: null },
  { name: "Justin Donovan", email: "justin.ashlandhomes@gmail.com", phone: null },
  { name: "Lisa Norvell", email: "lisabnorvell@gmail.com", phone: null },
  { name: "Marika Donovan", email: "marika.ashlandhomes@gmail.com", phone: null },
  { name: "Michaela Donovan", email: "michaela.ashlandhomes@gmail.com", phone: null },
  { name: "Susan Hearn", email: "susan.ashlandhomes@gmail.com", phone: null },
  { name: "Amanda Parker", email: "parkerhomerealestate@gmail.com", phone: "541-579-1010" },
  { name: "Rick Chesser", email: "rickchesser58@gmail.com", phone: "541-513-1060" },
  { name: "Kimberly Westenskow", email: "kimberly.westenskow@gmail.com", phone: "541-786-6621" },
  { name: "Kristie Albrecht", email: "kristiealbrecht@gmail.com", phone: "541-805-5871" },
  { name: "Mark Baker", email: "markbbroker@gmail.com", phone: "541-240-9252" },
  { name: "Marty Lien", email: "martylien@eoni.com", phone: "541-519-6886" },
  { name: "Tamara Claflin", email: "claflintamara@gmail.com", phone: "541-519-6607" },
  { name: "Toni Burton", email: "1toniburton@gmail.com", phone: "541-910-1337" },
  { name: "Gary Nolan", email: "gary.nolan@cascadehasson.com", phone: "503-799-7255" },
  { name: "Aaron Pontius", email: "aaron@theopt.com", phone: null },
  { name: "Alexa Heilbrun", email: "alexah@theopt.com", phone: null },
  { name: "Alix Edwards", email: "alix@theopt.com", phone: null },
  { name: "Allie Greiner", email: "allie@theopt.com", phone: null },
  { name: "Amy Emhoff", email: "amy@theopt.com", phone: null },
  { name: "Ana Campos", email: "ana@theopt.com", phone: null },
  { name: "Andy Aimone", email: "andy.a@theopt.com", phone: null },
  { name: "Ashley Hoogendam", email: "ashley@theopt.com", phone: null },
  { name: "Audrey Moore", email: "audrey@theopt.com", phone: null },
  { name: "Brian McCarthy", email: "brianm@theopt.com", phone: null },
  { name: "Brittany Koceski", email: "brittany@theopt.com", phone: null },
  { name: "Chris Haveman", email: "havemanhomes@theopt.com", phone: null },
  { name: "Colby J. Whitton", email: "colby@theopt.com", phone: null },
  { name: "Eric Ryan", email: "eric@theopt.com", phone: null },
  { name: "Erika Wrenn", email: "erika.wrenn@where-inc.com", phone: "503-312-9770" },
  { name: "Grant Gustafson", email: "grant@theopt.com", phone: null },
  { name: "Hanna Johnson", email: "hanna@theopt.com", phone: null },
  { name: "Jacob Weaver", email: "jacob@theopt.com", phone: null },
  { name: "Jess Johnson", email: "jess@theopt.com", phone: null },
  { name: "Jett Locke", email: "jett@theopt.com", phone: null },
  { name: "Jon Gooley", email: "jon@theopt.com", phone: null },
  { name: "Jordan Coleman", email: "jordan@theopt.com", phone: null },
  { name: "Joshua Cunningham", email: "joshua@theopt.com", phone: null },
  { name: "Justin Revilla", email: "justin@theopt.com", phone: null },
  { name: "Kelley Bailey", email: "kelley@theopt.com", phone: null },
  { name: "Lyric Haveman", email: "lyric@theopt.com", phone: null },
  { name: "Miranda Barnes", email: "miranda@theopt.com", phone: null },
  { name: "Molly Burke", email: "mollyb@theopt.com", phone: null },
  { name: "Monika Gray", email: "monika@theopt.com", phone: null },
  { name: "Narin Lay", email: "narin@theopt.com", phone: null },
  { name: "Rakesh Thomas", email: "rakesh@theopt.com", phone: null },
  { name: "Randolf Crescini", email: "randolf@theopt.com", phone: null },
  { name: "Ruth Maher", email: "ruth@theopt.com", phone: null },
  { name: "Sean Mele", email: "sean@theopt.com", phone: null },
  { name: "Sean Shepard", email: "shep@theopt.com", phone: null },
  { name: "Sheryl Lyons", email: "sheryl@theopt.com", phone: null },
  { name: "Sue Graff", email: "sue@theopt.com", phone: null },
  { name: "Tyson Hart", email: "tyson@theopt.com", phone: null },
  { name: "Westley Colebank", email: "westley@theopt.com", phone: null },
  { name: "Brant Mcmanamon", email: "brant@legacyre.com", phone: null },
  { name: "Brent Perry", email: "brent@legacyre.com", phone: null },
  { name: "James Hauge", email: "jamesh@legacyre.com", phone: null },
  { name: "Jared Hambrook", email: "jaredh@legacyre.com", phone: null },
  { name: "Jazmin Hayworth", email: "jazmin@legacyre.com", phone: null },
  { name: "Katelyn Hauge", email: "katelyn@legacyre.com", phone: null },
  { name: "Kathy Hauge", email: "kathyh@legacyre.com", phone: null },
  { name: "Morgan Vanderwall", email: "morgan@legacyre.com", phone: null },
  { name: "Phil Bailey", email: "phil@legacyre.com", phone: null },
  { name: "Kari Throop", email: "kari@karithroop.com", phone: "503-307-2056" },
];
