import { Share } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

/**
 * public/leadfinder-import.shortcut is a real, signed (--mode anyone) iOS
 * Shortcut generated by scripts/generate-shortcut.sh — not something built
 * at request time (signing needs macOS's `shortcuts` CLI, which Vercel's
 * build machine doesn't have). It POSTs whatever URL you share it to
 * straight to /api/import-listing with IMPORT_SHARE_SECRET baked in, so
 * re-run that script and recommit the file if the secret or domain change.
 */
export function ImportShortcutCard() {
  return (
    <Card className="p-4 mb-4 gap-3">
      <div className="flex items-center gap-2">
        <Share className="size-4 text-muted-foreground" />
        <h2 className="font-semibold text-foreground text-sm">Import from Zillow&rsquo;s Share Sheet</h2>
      </div>

      <p className="text-sm text-muted-foreground">
        On iPhone: open a listing in the Zillow app, tap Share, then add this Shortcut once below.
        After that it shows up right in the Share Sheet — no need to open LeadFinder at all.
      </p>

      <Button asChild className="self-start">
        <a href="/leadfinder-import.shortcut">
          <Share />
          Add to Shortcuts
        </a>
      </Button>
    </Card>
  );
}
